# Generated by Django 4.0 on 2021-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_disease_name_alter_disease_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="vaccines",
            field=models.ManyToManyField(blank=True, to="main.Vaccine"),
        ),
    ]
