# Generated by Django 4.0 on 2021-12-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_disease_vaccines"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccine",
            name="other_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
