# Generated by Django 4.0 on 2021-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_vaccine_other_url_vaccine_wikipedia_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccine",
            name="slug",
            field=models.CharField(default="vaccine-detail-example", max_length=100),
            preserve_default=False,
        ),
    ]
