# Generated by Django 4.0 on 2021-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_vaccine_slug_alter_vaccine_trade_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccine",
            name="vaccine_class",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
