# Generated by Django 6.0 on 2026-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccine",
            name="first_authorization_source_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="first_authorized_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="first_authorized_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
